/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

/**
 *
 * @author musta
 */
public class AddGradeDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddGradeDialog.class.getName());
    private final String currentStudentId;
    /**
     * Creates new form EnrollDialog
     */
    // FIX 1: Added the missing '(' before java.awt.Frame
    public AddGradeDialog(java.awt.Frame parent, boolean modal, String studentId, String studentName) {
        super(parent, modal);
        initComponents(); // DO NOT DELETE THIS LINE. NetBeans needs it.
        
        // Save the ID to our class variable
        this.currentStudentId = studentId;
        
        // FIX 2: Changed studentNameField to nameField to match your screenshot
        nameField.setText(studentName + " (" + studentId + ")");
        nameField.setEditable(false); 
        
        // 2. Fetch the live course names from the database model
        courseComboBox.removeAllItems();
        java.util.ArrayList<String> courses = models.Course.getAllCourseNames();
        for (String course : courses) {
            courseComboBox.addItem(course);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        courseComboBox = new javax.swing.JComboBox<>();
        marksField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        jLabel1.setText("Course :");

        jLabel2.setText("Studnet name:");

        jLabel3.setText("Marks");

        nameField.setEnabled(false);

        courseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel1.setLayout(new java.awt.GridLayout());

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(this::cancelBtnActionPerformed);
        jPanel1.add(cancelBtn);

        saveBtn.setText("Save");
        saveBtn.addActionListener(this::saveBtnActionPerformed);
        jPanel1.add(saveBtn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameField)
                    .addComponent(marksField)
                    .addComponent(courseComboBox, 0, 253, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(courseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(marksField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String selectedCourseName = courseComboBox.getSelectedItem().toString();
        String rawMarks = marksField.getText().trim();

        // STEP 1: Strict Marks Validation (Blocks letters, allows decimals)
        if (!rawMarks.matches("^\\d+(\\.\\d+)?$")) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Marks must be a valid number (e.g., 70 or 85.5) and cannot contain letters.", 
                "Validation Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        double validMarks = Double.parseDouble(rawMarks);
        if (validMarks < 0 || validMarks > 100) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Marks must be between 0 and 100.", 
                "Validation Error", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // STEP 2: Translate Course Name to Course ID (e.g., "Cybersecurity 101" -> "CYB201")
        String courseId = models.Course.getIdByName(selectedCourseName);
        if (courseId == null) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "System error: Could not find course ID.", 
                "Database Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // STEP 3: Duplicate Enrollment Check
        if (models.Student.checkEnrollmentExists(this.currentStudentId, courseId)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "This student already has a mark for " + selectedCourseName + ".\nIf you need to change it, please use the 'Update' button.", 
                "Student Already Enrolled", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return; 
        }

        // STEP 4: Database Insertion (Using the Model!)
        try {
            // We hand the clean, validated data directly to the backend
            models.Student.addGrade(this.currentStudentId, courseId, validMarks);

            // Success! Show message and close the dialog
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Grade added successfully!", 
                "Success", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); 
            
        } catch (java.sql.SQLException ex) {
            // The backend caught an error and threw it here for the UI to display
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Database Error: " + ex.getMessage(), 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<String> courseComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField marksField;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
