/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author musta
 */
public class MainPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainPage.class.getName());

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        this.setSize(1024, 870);
        this.setLocationRelativeTo(null); 
        
        // NEW: Load the data immediately when the app opens!
        refreshStudentTable();
        // This watches the table to see if a row is highlighted
        studentTable.getSelectionModel().addListSelectionListener((javax.swing.event.ListSelectionEvent event) -> {
            // Ignore extra events while the user is dragging their mouse
            if (!event.getValueIsAdjusting()) {
                
                // .getSelectedRow() returns -1 if absolutely nothing is clicked
                if (studentTable.getSelectedRow() != -1) {
                    // A row is selected! Turn the button ON.
                    addGradeBtn.setEnabled(true);
                    updateBtn.setEnabled(true);
                    deleteBtn.setEnabled(true);
                    addGradeBtn.setToolTipText("Click to enroll the sele^cted student into a new course.");
                    updateBtn.setToolTipText("Click to enroll the selected student into a new course.");
                    deleteBtn.setToolTipText("Click to enroll the selected student into a new course.");
                } else {
                    // Nothing is selected! Turn the button OFF.
                    addGradeBtn.setEnabled(false);
                    addGradeBtn.setToolTipText("Select a student from the table first to enroll them.");
                    updateBtn.setEnabled(false);
                    deleteBtn.setEnabled(false);
                    updateBtn.setToolTipText("Select a student from the table first to enroll them.");
                    deleteBtn.setToolTipText("Select a student from the table first to enroll them.");
                }
            }
        });
        
        myTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            
            int activeTab = myTabbedPane.getSelectedIndex();
            
            if (activeTab == 0) {
                // User clicked the Student Tab
                addGradeBtn.setVisible(true);  // Show the Add Grade button
                statusLabel.setText("Status: Viewing Student Management.");
            } else if (activeTab == 1) {
                // User clicked the Course Tab
                addGradeBtn.setVisible(false); // Hide the Add Grade button!
                statusLabel.setText("Status: Viewing Course Management.");
            }
            
        }
    });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        myTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        Searchlabel = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        searchTypeComboBox = new javax.swing.JComboBox<>();
        sortIdRadio = new javax.swing.JRadioButton();
        sortNameRadio = new javax.swing.JRadioButton();
        sortMarksRadio = new javax.swing.JRadioButton();
        passingCheckBox = new javax.swing.JCheckBox();
        marksSlider = new javax.swing.JSlider();
        sliderLabel = new javax.swing.JLabel();
        showAllBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        addGradeBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileBtn = new javax.swing.JMenu();
        printBtn = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitBtn = new javax.swing.JMenuItem();
        aboutBtn = new javax.swing.JMenu();
        helpBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(30, 30, 30));
        setPreferredSize(new java.awt.Dimension(1024, 870));

        jPanel1.setPreferredSize(new java.awt.Dimension(1015, 865));

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Email", "Course", "Mark"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(studentTable);

        Searchlabel.setText("Search by:");

        searchField.addActionListener(this::searchFieldActionPerformed);
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(this::searchBtnActionPerformed);

        searchTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student ID", "Student Name", "Course" }));
        searchTypeComboBox.addActionListener(this::searchTypeComboBoxActionPerformed);

        buttonGroup1.add(sortIdRadio);
        sortIdRadio.setSelected(true);
        sortIdRadio.setText("Sort by ID");
        sortIdRadio.addActionListener(this::sortIdRadioActionPerformed);

        buttonGroup1.add(sortNameRadio);
        sortNameRadio.setText("Sort by Name");
        sortNameRadio.addActionListener(this::sortNameRadioActionPerformed);

        buttonGroup1.add(sortMarksRadio);
        sortMarksRadio.setText("Sort by Marks");
        sortMarksRadio.addActionListener(this::sortMarksRadioActionPerformed);

        passingCheckBox.setText("Show Passing Only (50+)");
        passingCheckBox.addActionListener(this::passingCheckBoxActionPerformed);

        marksSlider.setMinorTickSpacing(20);
        marksSlider.setPaintLabels(true);
        marksSlider.setPaintTicks(true);
        marksSlider.setValue(0);
        marksSlider.addChangeListener(this::marksSliderStateChanged);

        sliderLabel.setText("Min Marks: 0");

        showAllBtn.setText("All Student");
        showAllBtn.addActionListener(this::showAllBtnActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(searchTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(searchBtn)
                                .addGap(18, 18, 18)
                                .addComponent(showAllBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sortIdRadio)
                                .addGap(18, 18, 18)
                                .addComponent(sortNameRadio)
                                .addGap(18, 18, 18)
                                .addComponent(sortMarksRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passingCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sliderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(marksSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Searchlabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Searchlabel)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn)
                    .addComponent(searchTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showAllBtn))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortIdRadio)
                    .addComponent(sortNameRadio)
                    .addComponent(sortMarksRadio)
                    .addComponent(passingCheckBox)
                    .addComponent(marksSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sliderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        myTabbedPane.addTab("Student", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );

        myTabbedPane.addTab("Course Mangement", jPanel2);

        getContentPane().add(myTabbedPane, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        addBtn.setText("Add");
        addBtn.addActionListener(this::addBtnActionPerformed);
        jPanel3.add(addBtn);

        addGradeBtn.setText("Add Grade");
        addGradeBtn.setEnabled(false);
        addGradeBtn.addActionListener(this::addGradeBtnActionPerformed);
        jPanel3.add(addGradeBtn);

        updateBtn.setText("Update");
        updateBtn.setEnabled(false);
        updateBtn.addActionListener(this::updateBtnActionPerformed);
        jPanel3.add(updateBtn);

        deleteBtn.setText("Delete");
        deleteBtn.setEnabled(false);
        deleteBtn.addActionListener(this::deleteBtnActionPerformed);
        jPanel3.add(deleteBtn);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("System Ready.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.NORTH);

        fileBtn.setText("File");

        printBtn.setText("print");
        printBtn.addActionListener(this::printBtnActionPerformed);
        fileBtn.add(printBtn);
        fileBtn.add(jSeparator1);

        exitBtn.setText("Exit");
        exitBtn.addActionListener(this::exitBtnActionPerformed);
        fileBtn.add(exitBtn);

        jMenuBar1.add(fileBtn);

        aboutBtn.setText("about");
        jMenuBar1.add(aboutBtn);

        helpBtn.setText("help");
        jMenuBar1.add(helpBtn);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // Ask the TabbedPane which tab the user is currently looking at
        int currentTab = myTabbedPane.getSelectedIndex();
        if (currentTab == 0) {
        // --- STUDENT TAB LOGIC ---
        AddStudentDialog dialog = new AddStudentDialog(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        refreshStudentTable(); 
        statusLabel.setText("Status: Student added successfully.");

    } else if (currentTab == 1) {
        // --- COURSE TAB LOGIC ---
        // You will build this dialog next!
        AddCourseDialog dialog = new AddCourseDialog(this, true); 
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        refreshCourseTable(); 
        statusLabel.setText("Status: Course added successfully.");
    }
    }//GEN-LAST:event_addBtnActionPerformed

    private void searchTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTypeComboBoxActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printBtnActionPerformed

    private void sortNameRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortNameRadioActionPerformed
        refreshStudentTable();
    }//GEN-LAST:event_sortNameRadioActionPerformed

    private void passingCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passingCheckBoxActionPerformed
        refreshStudentTable();
    }//GEN-LAST:event_passingCheckBoxActionPerformed

    private void marksSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_marksSliderStateChanged
        // 1. Instantly update the label the moment the mouse moves. 
    // This gives the user real-time visual feedback!
    int currentVal = marksSlider.getValue();
    sliderLabel.setText("Min Marks: " + currentVal);

    // 2. The "Senior Dev" Optimization:
    // .getValueIsAdjusting() is TRUE while the user is holding the mouse down.
    // It becomes FALSE the exact millisecond they let go.
    if (!marksSlider.getValueIsAdjusting()) {
        // Only run the heavy database query when they finish dragging!
        refreshStudentTable();
    }
    }//GEN-LAST:event_marksSliderStateChanged

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        refreshStudentTable();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void showAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllBtnActionPerformed
        searchField.setText("");
        marksSlider.setValue(0);
        passingCheckBox.setSelected(false);
        sortIdRadio.setSelected(true);
        refreshStudentTable();
    }//GEN-LAST:event_showAllBtnActionPerformed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        refreshStudentTable();
    }//GEN-LAST:event_searchFieldKeyReleased

    private void sortIdRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortIdRadioActionPerformed
        refreshStudentTable();
    }//GEN-LAST:event_sortIdRadioActionPerformed

    private void sortMarksRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortMarksRadioActionPerformed
        refreshStudentTable();
    }//GEN-LAST:event_sortMarksRadioActionPerformed

    private void addGradeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGradeBtnActionPerformed
        int selectedRow = studentTable.getSelectedRow();
    
    if (selectedRow != -1) {
        // Grab the ID (Column 0) and Name (Column 1) from the highlighted row
        String studentId = studentTable.getValueAt(selectedRow, 0).toString();
        String studentName = studentTable.getValueAt(selectedRow, 1).toString();
        
        // Pass them into the new pop-up
        AddGradeDialog dialog = new AddGradeDialog(this, true, studentId, studentName);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        
        // Refresh the table when the pop-up closes
        refreshStudentTable(); 
    }
    }//GEN-LAST:event_addGradeBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        int selectedRow = studentTable.getSelectedRow();
    
        if (selectedRow != -1) {
            // Grab EVERYTHING from the highlighted row
            String id = studentTable.getValueAt(selectedRow, 0).toString();
            String name = studentTable.getValueAt(selectedRow, 1).toString();
            String email = studentTable.getValueAt(selectedRow, 2).toString();
            String course = studentTable.getValueAt(selectedRow, 3).toString();
            String mark = studentTable.getValueAt(selectedRow, 4).toString();

            // Open the pop-up and hand it the data!
            UpdateDialog dialog = new UpdateDialog(this, true, id, name, email, course, mark);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);

            // Refresh the table when they are done
            refreshStudentTable();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a student from the table first.");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int selectedRow = studentTable.getSelectedRow();
    
        if (selectedRow != -1) {
            // 1. Grab the necessary data from the table
            String studentId = studentTable.getValueAt(selectedRow, 0).toString();
            String studentName = studentTable.getValueAt(selectedRow, 1).toString();
            String courseName = studentTable.getValueAt(selectedRow, 3).toString();

            // 2. Defensive UI: The Confirmation Dialog
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to completely remove the grade for " + studentName + " in " + courseName + "?\n\nThis action cannot be undone.", 
                "Confirm Delete", 
                javax.swing.JOptionPane.YES_NO_OPTION, 
                javax.swing.JOptionPane.WARNING_MESSAGE);

            // 3. If they click "Yes"
            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                try {
                    // Translate the friendly name ("Cybersecurity 101") back to the ID ("CYB201")
                    String courseId = models.Course.getIdByName(courseName);

                    if (courseId == null) {
                        throw new RuntimeException("System error: Could not resolve Course ID.");
                    }

                    // Pack the DTO Suitcase
                    models.Student studentToDelete = new models.Student();
                    studentToDelete.setId(studentId);
                    studentToDelete.setCourse(courseId);

                    // Execute the backend deletion
                    studentToDelete.deleteEnrollment();

                    // Success! Refresh the table instantly
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        "Record deleted successfully.", 
                        "Deleted", 
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    refreshStudentTable();

                } catch (RuntimeException ex) {
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        ex.getMessage(), 
                        "Delete Failed", 
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            // If they click Delete without highlighting a row first
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Please select a record from the table to delete.", 
                "Select a Record", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainPage().setVisible(true));
    }
    
    private void refreshStudentTable() {
    // 1. The JOIN Query: We stitch all three tables together!
    // We use aliases (s, e, c) to make typing the table names shorter.
    StringBuilder sql = new StringBuilder(
        "SELECT s.student_id, s.name, s.email, c.course_name, e.mark " +
        "FROM students s " +
        "JOIN enrollments e ON s.student_id = e.student_id " +
        "JOIN courses c ON e.course_id = c.course_id " +
        "WHERE 1=1 "
    );
    
    // 2. Read the Search Bar (Notice we have to specify WHICH table the column is in)
    String keyword = searchField.getText().trim();
    
    if (!keyword.isEmpty()) {
        // Find out what the user selected in the dropdown
        String searchCategory = searchTypeComboBox.getSelectedItem().toString();
        
        // Append a specific SQL rule based on their choice
        if (searchCategory.equals("Student Name")) {
            sql.append("AND s.name LIKE '%").append(keyword).append("%' ");
            
        } else if (searchCategory.equals("Student ID")) {
            sql.append("AND s.student_id LIKE '%").append(keyword).append("%' ");
            
        } else if (searchCategory.equals("Course")) {
            sql.append("AND c.course_name LIKE '%").append(keyword).append("%' ");
            
        } else if (searchCategory.equals("Email")) {
            sql.append("AND s.email LIKE '%").append(keyword).append("%' ");
        }
    }
    
    // 3. Read the JSlider
    int minMarks = marksSlider.getValue();
    if (minMarks > 0) {
        sql.append("AND e.mark >= ").append(minMarks).append(" ");
    }
    
    // 4. Read the JCheckBox
    if (passingCheckBox.isSelected()) {
        sql.append("AND e.mark >= 50 ");
    }
    
    // 5. Read the JRadioButtons
    if (sortNameRadio.isSelected()) {
        sql.append("ORDER BY s.name ASC");
    } else if (sortMarksRadio.isSelected()) {
        sql.append("ORDER BY e.mark DESC"); 
    } else {
        sql.append("ORDER BY s.student_id ASC");
    }

    // 6. Execute the Query and Update the JTable
    try (java.sql.Connection conn = database.DBConnection.getConnection();
         java.sql.Statement stmt = conn.createStatement();
         java.sql.ResultSet rs = stmt.executeQuery(sql.toString())) {
         
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) studentTable.getModel();
        model.setRowCount(0); 
        
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("student_id"),
                rs.getString("name"),
                rs.getString("email"),
                // Grab the joined columns!
                rs.getString("course_name"), 
                rs.getDouble("mark")          
            });
        }
        
        statusLabel.setText("System Ready. Data loaded successfully.");
        statusLabel.setForeground(new java.awt.Color(0, 153, 51)); // Dark Green
        
    } catch (java.sql.SQLException ex) {
        statusLabel.setText("Database error: " + ex.getMessage());
        statusLabel.setForeground(java.awt.Color.RED);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Searchlabel;
    private javax.swing.JMenu aboutBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addGradeBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JMenuItem exitBtn;
    private javax.swing.JMenu fileBtn;
    private javax.swing.JMenu helpBtn;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSlider marksSlider;
    private javax.swing.JTabbedPane myTabbedPane;
    private javax.swing.JCheckBox passingCheckBox;
    private javax.swing.JMenuItem printBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JComboBox<String> searchTypeComboBox;
    private javax.swing.JButton showAllBtn;
    private javax.swing.JLabel sliderLabel;
    private javax.swing.JRadioButton sortIdRadio;
    private javax.swing.JRadioButton sortMarksRadio;
    private javax.swing.JRadioButton sortNameRadio;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTable studentTable;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
