/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author musta
 */
public class MainPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainPage.class.getName());

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        this.setSize(1024, 870);
        this.setLocationRelativeTo(null); 
        
        // NEW: Load the data immediately when the app opens!
        refreshTable();
        // This watches the table to see if a row is highlighted
        // ==========================================
        // 1. STUDENT TABLE LISTENER
        // ==========================================
        studentTable.getSelectionModel().addListSelectionListener((javax.swing.event.ListSelectionEvent event) -> {
            if (!event.getValueIsAdjusting()) {
                if (studentTable.getSelectedRow() != -1) {
                    addGradeBtn.setEnabled(true);
                    updateBtn.setEnabled(true);
                    deleteBtn.setEnabled(true);
                    
                    addGradeBtn.setToolTipText("Click to enroll this student into a new course.");
                    updateBtn.setToolTipText("Click to update this student's details.");
                    deleteBtn.setToolTipText("Click to completely delete this enrollment record.");
                } else {
                    addGradeBtn.setEnabled(false);
                    updateBtn.setEnabled(false);
                    deleteBtn.setEnabled(false);
                    
                    addGradeBtn.setToolTipText("Select a student from the table first.");
                    updateBtn.setToolTipText("Select a student from the table first.");
                    deleteBtn.setToolTipText("Select a student from the table first.");
                }
            }
        });

        // ==========================================
        // 2. COURSE TABLE LISTENER
        // ==========================================
        courseTable.getSelectionModel().addListSelectionListener((javax.swing.event.ListSelectionEvent event) -> {
            if (!event.getValueIsAdjusting()) {
                
                // FIXED: Now checks the courseTable!
                if (courseTable.getSelectedRow() != -1) { 
                    updateBtn.setEnabled(true);
                    deleteBtn.setEnabled(true);
                    
                    // FIXED: Course-specific tooltips
                    updateBtn.setToolTipText("Click to update this course's name.");
                    deleteBtn.setToolTipText("Click to delete this course.");
                } else {
                    updateBtn.setEnabled(false);
                    deleteBtn.setEnabled(false);
                    
                    updateBtn.setToolTipText("Select a course from the table first.");
                    deleteBtn.setToolTipText("Select a course from the table first.");
                }
            }
        });
        
        // ==========================================
        // 3. TABBED PANE LISTENER
        // ==========================================
        myTabbedPane.addChangeListener((javax.swing.event.ChangeEvent evt) -> {
            int activeTab = myTabbedPane.getSelectedIndex();
            
            // PRO-TIP: Reset all buttons to OFF when switching tabs for safety
            addGradeBtn.setEnabled(false);
            updateBtn.setEnabled(false);
            deleteBtn.setEnabled(false);
            
            if (activeTab == 0) {
                // User clicked the Student Tab
                addGradeBtn.setVisible(true);  
                statusLabel.setText("Status: Viewing Student Management.");
            } else if (activeTab == 1) {
                // User clicked the Course Tab
                addGradeBtn.setVisible(false); 
                statusLabel.setText("Status: Viewing Course Management.");
            }
            
            refreshTable();
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        myTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        Searchlabel = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        searchTypeComboBox = new javax.swing.JComboBox<>();
        sortIdRadio = new javax.swing.JRadioButton();
        sortNameRadio = new javax.swing.JRadioButton();
        sortMarksRadio = new javax.swing.JRadioButton();
        passingCheckBox = new javax.swing.JCheckBox();
        marksSlider = new javax.swing.JSlider();
        sliderLabel = new javax.swing.JLabel();
        showAllBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        courseTable = new javax.swing.JTable();
        Searchlabel1 = new javax.swing.JLabel();
        searchField1 = new javax.swing.JTextField();
        searchBtn1 = new javax.swing.JButton();
        sortIdRadio1 = new javax.swing.JRadioButton();
        sortNameRadio1 = new javax.swing.JRadioButton();
        showAllBtn1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        addGradeBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileBtn = new javax.swing.JMenu();
        printBtn = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitBtn = new javax.swing.JMenuItem();
        aboutBtn = new javax.swing.JMenu();
        helpBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(30, 30, 30));
        setPreferredSize(new java.awt.Dimension(1024, 870));

        jPanel1.setPreferredSize(new java.awt.Dimension(1015, 865));

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Email", "Course", "Mark"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(studentTable);
        if (studentTable.getColumnModel().getColumnCount() > 0) {
            studentTable.getColumnModel().getColumn(2).setHeaderValue("Email");
            studentTable.getColumnModel().getColumn(3).setHeaderValue("Course");
            studentTable.getColumnModel().getColumn(4).setHeaderValue("Mark");
        }

        Searchlabel.setText("Search by:");

        searchField.addActionListener(this::searchFieldActionPerformed);
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(this::searchBtnActionPerformed);

        searchTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student ID", "Student Name", "Course" }));
        searchTypeComboBox.addActionListener(this::searchTypeComboBoxActionPerformed);

        buttonGroup1.add(sortIdRadio);
        sortIdRadio.setText("Sort by ID");
        sortIdRadio.addActionListener(this::sortIdRadioActionPerformed);

        buttonGroup1.add(sortNameRadio);
        sortNameRadio.setText("Sort by Name");
        sortNameRadio.addActionListener(this::sortNameRadioActionPerformed);

        buttonGroup1.add(sortMarksRadio);
        sortMarksRadio.setText("Sort by Marks");
        sortMarksRadio.addActionListener(this::sortMarksRadioActionPerformed);

        passingCheckBox.setText("Show Passing Only (50+)");
        passingCheckBox.addActionListener(this::passingCheckBoxActionPerformed);

        marksSlider.setMinorTickSpacing(20);
        marksSlider.setPaintLabels(true);
        marksSlider.setPaintTicks(true);
        marksSlider.setValue(0);
        marksSlider.addChangeListener(this::marksSliderStateChanged);

        sliderLabel.setText("Min Marks: 0");

        showAllBtn.setText("All Student");
        showAllBtn.addActionListener(this::showAllBtnActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(searchTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(searchBtn)
                                .addGap(18, 18, 18)
                                .addComponent(showAllBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sortIdRadio)
                                .addGap(18, 18, 18)
                                .addComponent(sortNameRadio)
                                .addGap(18, 18, 18)
                                .addComponent(sortMarksRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passingCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sliderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(marksSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Searchlabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Searchlabel)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn)
                    .addComponent(searchTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showAllBtn))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortIdRadio)
                    .addComponent(sortNameRadio)
                    .addComponent(sortMarksRadio)
                    .addComponent(passingCheckBox)
                    .addComponent(marksSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sliderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        myTabbedPane.addTab("Student", jPanel1);

        courseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Course ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(courseTable);

        Searchlabel1.setText("Search by name:");

        searchField1.addActionListener(this::searchField1ActionPerformed);
        searchField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchField1KeyReleased(evt);
            }
        });

        searchBtn1.setText("Search");
        searchBtn1.addActionListener(this::searchBtn1ActionPerformed);

        buttonGroup1.add(sortIdRadio1);
        sortIdRadio1.setSelected(true);
        sortIdRadio1.setText("Sort by ID");
        sortIdRadio1.addActionListener(this::sortIdRadio1ActionPerformed);

        buttonGroup1.add(sortNameRadio1);
        sortNameRadio1.setText("Sort by Name");
        sortNameRadio1.addActionListener(this::sortNameRadio1ActionPerformed);

        showAllBtn1.setText("All Course");
        showAllBtn1.addActionListener(this::showAllBtn1ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(sortIdRadio1)
                                .addGap(18, 18, 18)
                                .addComponent(sortNameRadio1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Searchlabel1)
                                .addGap(34, 34, 34)
                                .addComponent(searchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(searchBtn1)
                                .addGap(59, 59, 59)
                                .addComponent(showAllBtn1)))
                        .addContainerGap(327, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn1)
                    .addComponent(showAllBtn1)
                    .addComponent(Searchlabel1))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortIdRadio1)
                    .addComponent(sortNameRadio1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        myTabbedPane.addTab("Course Mangement", jPanel2);

        getContentPane().add(myTabbedPane, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        addBtn.setText("Add");
        addBtn.addActionListener(this::addBtnActionPerformed);
        jPanel3.add(addBtn);

        addGradeBtn.setText("Add Grade");
        addGradeBtn.setEnabled(false);
        addGradeBtn.addActionListener(this::addGradeBtnActionPerformed);
        jPanel3.add(addGradeBtn);

        updateBtn.setText("Update");
        updateBtn.setEnabled(false);
        updateBtn.addActionListener(this::updateBtnActionPerformed);
        jPanel3.add(updateBtn);

        deleteBtn.setText("Delete");
        deleteBtn.setEnabled(false);
        deleteBtn.addActionListener(this::deleteBtnActionPerformed);
        jPanel3.add(deleteBtn);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("System Ready.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.NORTH);

        fileBtn.setText("File");

        printBtn.setText("print");
        printBtn.addActionListener(this::printBtnActionPerformed);
        fileBtn.add(printBtn);
        fileBtn.add(jSeparator1);

        exitBtn.setText("Exit");
        exitBtn.addActionListener(this::exitBtnActionPerformed);
        fileBtn.add(exitBtn);

        jMenuBar1.add(fileBtn);

        aboutBtn.setText("about");
        jMenuBar1.add(aboutBtn);

        helpBtn.setText("help");
        jMenuBar1.add(helpBtn);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // Ask the TabbedPane which tab the user is currently looking at
        int currentTab = myTabbedPane.getSelectedIndex();
        if (currentTab == 0) {
        // --- STUDENT TAB LOGIC ---
        AddStudentDialog dialog = new AddStudentDialog(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        refreshTable(); 
        statusLabel.setText("Status: Student added successfully.");

    } else if (currentTab == 1) {
        // --- COURSE TAB LOGIC ---
        // You will build this dialog next!
        AddCourseDialog dialog = new AddCourseDialog(this, true); 
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        refreshTable(); 
        statusLabel.setText("Status: Course added successfully.");
    }
    }//GEN-LAST:event_addBtnActionPerformed

    private void searchTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTypeComboBoxActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printBtnActionPerformed

    private void sortNameRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortNameRadioActionPerformed
        refreshTable();
    }//GEN-LAST:event_sortNameRadioActionPerformed

    private void passingCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passingCheckBoxActionPerformed
        refreshTable();
    }//GEN-LAST:event_passingCheckBoxActionPerformed

    private void marksSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_marksSliderStateChanged
        // 1. Instantly update the label the moment the mouse moves. 
    // This gives the user real-time visual feedback!
    int currentVal = marksSlider.getValue();
    sliderLabel.setText("Min Marks: " + currentVal);

    // 2. The "Senior Dev" Optimization:
    // .getValueIsAdjusting() is TRUE while the user is holding the mouse down.
    // It becomes FALSE the exact millisecond they let go.
    if (!marksSlider.getValueIsAdjusting()) {
        // Only run the heavy database query when they finish dragging!
        refreshTable();
    }
    }//GEN-LAST:event_marksSliderStateChanged

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        refreshTable();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void showAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllBtnActionPerformed
        searchField.setText("");
        marksSlider.setValue(0);
        passingCheckBox.setSelected(false);
        sortIdRadio.setSelected(true);
        refreshTable();
    }//GEN-LAST:event_showAllBtnActionPerformed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        refreshTable();
    }//GEN-LAST:event_searchFieldKeyReleased

    private void sortIdRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortIdRadioActionPerformed
        refreshTable();
    }//GEN-LAST:event_sortIdRadioActionPerformed

    private void sortMarksRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortMarksRadioActionPerformed
        refreshTable();
    }//GEN-LAST:event_sortMarksRadioActionPerformed

    private void addGradeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGradeBtnActionPerformed
        int selectedRow = studentTable.getSelectedRow();
    
    if (selectedRow != -1) {
        // Grab the ID (Column 0) and Name (Column 1) from the highlighted row
        String studentId = studentTable.getValueAt(selectedRow, 0).toString();
        String studentName = studentTable.getValueAt(selectedRow, 1).toString();
        
        // Pass them into the new pop-up
        AddGradeDialog dialog = new AddGradeDialog(this, true, studentId, studentName);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        
        // Refresh the table when the pop-up closes
        refreshTable(); 
    }
    }//GEN-LAST:event_addGradeBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        int currentTab = myTabbedPane.getSelectedIndex();
    
    if (currentTab == 0) {
        // ==========================================
        //           STUDENT TAB LOGIC
        // ==========================================
        int selectedRow = studentTable.getSelectedRow();
        
        if (selectedRow != -1) {
            // Grab the 5 columns from the Student table
            String id = studentTable.getValueAt(selectedRow, 0).toString();
            String name = studentTable.getValueAt(selectedRow, 1).toString();
            String email = studentTable.getValueAt(selectedRow, 2).toString();
            String course = studentTable.getValueAt(selectedRow, 3).toString();
            String mark = studentTable.getValueAt(selectedRow, 4).toString();
            
            // Open the Student Update Dialog
            UpdateStudentDialog dialog = new UpdateStudentDialog(this, true, id, name, email, course, mark);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
            
            refreshTable(); // Instantly reload the screen!
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a student from the table first.");
        }
        
    } else if (currentTab == 1) {
        // ==========================================
        //           COURSE TAB LOGIC
        // ==========================================
        int selectedRow = courseTable.getSelectedRow(); // Make sure this matches your Course table variable!
        
        if (selectedRow != -1) {
            // Grab the 2 columns from the Course table
            String courseId = courseTable.getValueAt(selectedRow, 0).toString();
            String courseName = courseTable.getValueAt(selectedRow, 1).toString();
            
            // Open the Course Update Dialog (We will build this next!)
            UpdateCourseDialog dialog = new UpdateCourseDialog(this, true, courseId, courseName);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
            
            refreshTable(); // Instantly reload the screen!
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a course from the table first.");
        }
    }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int currentTab = myTabbedPane.getSelectedIndex();
    
    if (currentTab == 0) {
        // ==========================================
        //           STUDENT TAB LOGIC
        // ==========================================
        int selectedRow = studentTable.getSelectedRow();
        
        if (selectedRow != -1) {
            String studentId = studentTable.getValueAt(selectedRow, 0).toString();
            String studentName = studentTable.getValueAt(selectedRow, 1).toString();
            String courseName = studentTable.getValueAt(selectedRow, 3).toString();

            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to completely remove the grade for " + studentName + " in " + courseName + "?\n\nThis action cannot be undone.", 
                "Confirm Delete", 
                javax.swing.JOptionPane.YES_NO_OPTION, 
                javax.swing.JOptionPane.WARNING_MESSAGE);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                try {
                    String courseId = models.Course.getIdByName(courseName);
                    models.Student studentToDelete = new models.Student();
                    studentToDelete.setId(studentId);
                    studentToDelete.setCourse(courseId);
                    
                    studentToDelete.deleteEnrollment();

                    javax.swing.JOptionPane.showMessageDialog(this, "Record deleted successfully.");
                    refreshTable(); // Refresh the screen!
                    
                } catch (RuntimeException ex) {
                    javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Delete Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a student from the table first.");
        }
        
    } else if (currentTab == 1) {
        // ==========================================
        //           COURSE TAB LOGIC
        // ==========================================
        int selectedRow = courseTable.getSelectedRow();
        
        if (selectedRow != -1) {
            String courseId = courseTable.getValueAt(selectedRow, 0).toString();
            String courseName = courseTable.getValueAt(selectedRow, 1).toString();
            System.out.println("DEBUG: Trying to delete Course ID: [" + courseId + "]");
            System.out.println("DEBUG: Trying to delete Course Name: [" + courseName + "]");
            // DEFENSIVE UI: Warn them that this deletes grades too!
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to completely delete the course '" + courseName + "'?\n\nWARNING: This will also erase all student grades associated with this course. This action cannot be undone.", 
                "Confirm Course Deletion", 
                javax.swing.JOptionPane.YES_NO_OPTION, 
                javax.swing.JOptionPane.ERROR_MESSAGE); // Use ERROR_MESSAGE for a scary red icon

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                try {
                    models.Course courseToDelete = new models.Course();
                    courseToDelete.setCourseId(courseId);
                    
                    courseToDelete.delete(); // Calls our new transaction method!

                    javax.swing.JOptionPane.showMessageDialog(this, "Course and associated grades deleted successfully.");
                    refreshTable(); // Refresh the screen!
                    
                } catch (RuntimeException ex) {
                    javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Delete Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a course from the table first.");
        }
    }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchField1ActionPerformed
        
    }//GEN-LAST:event_searchField1ActionPerformed

    private void searchField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchField1KeyReleased
        refreshTable();
    }//GEN-LAST:event_searchField1KeyReleased

    private void searchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn1ActionPerformed
        refreshTable();
    }//GEN-LAST:event_searchBtn1ActionPerformed

    private void sortIdRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortIdRadio1ActionPerformed
        refreshTable();
    }//GEN-LAST:event_sortIdRadio1ActionPerformed

    private void sortNameRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortNameRadio1ActionPerformed
        refreshTable();
    }//GEN-LAST:event_sortNameRadio1ActionPerformed

    private void showAllBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllBtn1ActionPerformed
        searchField1.setText("");
        sortIdRadio1.setSelected(true);
        refreshTable();
    }//GEN-LAST:event_showAllBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainPage().setVisible(true));
    }
    
    private void refreshTable() {
        int activeTab = myTabbedPane.getSelectedIndex();

            if (activeTab == 0) {
                // ==========================================
                //           STUDENT TAB LOGIC
                // ==========================================
                String keyword = searchField.getText().trim();

                String sortBy = "ID"; 
                if (sortNameRadio.isSelected()) sortBy = "NAME";
                else if (sortMarksRadio.isSelected()) sortBy = "MARKS";

                double minMarks = passingCheckBox.isSelected() ? 50.0 : marksSlider.getValue();

                // Ask Student model for data
                java.util.ArrayList<Object[]> data = models.Student.getData(keyword, sortBy, minMarks);

                // Paint Student Table
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) studentTable.getModel();
                model.setRowCount(0); 
                for (Object[] row : data) {
                    model.addRow(row); 
                }

            } else if (activeTab == 1) {
                // ==========================================
                //           COURSE TAB LOGIC
                // ==========================================
                String keyword = searchField1.getText().trim();
                boolean sortByName = sortNameRadio1.isSelected();
                
                // Ask Course model for data
                java.util.ArrayList<String[]> data = models.Course.getData(keyword, sortByName);
                
                // Paint Course Table
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) courseTable.getModel();
                model.setRowCount(0); 
                for (String[] row : data) {
                    model.addRow(row); 
                }
            }
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Searchlabel;
    private javax.swing.JLabel Searchlabel1;
    private javax.swing.JMenu aboutBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addGradeBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable courseTable;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JMenuItem exitBtn;
    private javax.swing.JMenu fileBtn;
    private javax.swing.JMenu helpBtn;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSlider marksSlider;
    private javax.swing.JTabbedPane myTabbedPane;
    private javax.swing.JCheckBox passingCheckBox;
    private javax.swing.JMenuItem printBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton searchBtn1;
    private javax.swing.JTextField searchField;
    private javax.swing.JTextField searchField1;
    private javax.swing.JComboBox<String> searchTypeComboBox;
    private javax.swing.JButton showAllBtn;
    private javax.swing.JButton showAllBtn1;
    private javax.swing.JLabel sliderLabel;
    private javax.swing.JRadioButton sortIdRadio;
    private javax.swing.JRadioButton sortIdRadio1;
    private javax.swing.JRadioButton sortMarksRadio;
    private javax.swing.JRadioButton sortNameRadio;
    private javax.swing.JRadioButton sortNameRadio1;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTable studentTable;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
